export const TOGGLE_MESSAGES = 'TOGGLE_MESSAGES';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_NAV_CLASS = 'UPDATE_NAV_CLASS';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const UPDATE_UID = 'UPDATE_UID';
export const TOGGLE_USER_LOGIN = 'TOGGLE_USER_LOGIN';
